auto/history: fix flaky test Test_automation_applyConfig
This occasionally fails with errors like:

    --- FAIL: Test_automation_applyConfig (10.02s)
    factory_test.go:188:   int32(
    -  2,
    +  1,
    )
    occupancy
    FAIL
    FAIL github.com/smart-core-os/sc-bos/pkg/auto/history 11.064s

Contributing factors:
1. Use of random values, which could produce no change from the previous
 value and therefore fewer changes than expected
2. Timing variation caused by polling schedules racing with test
sampling code

To resolve this:
1. Use synctest to ensure deterministic test timing
2. Use deterministic values in tests.