driver/proxy: fix TestDeviceFetcher_Pull intermittent failure
Test can fail intermittently:
    --- FAIL: TestDeviceFetcher_Pull (0.00s)
        --- FAIL: TestDeviceFetcher_Pull/streams_changes (0.00s)
            devices_test.go:225: expected device1, got test
    FAIL
    FAIL	github.com/smart-core-os/sc-bos/pkg/driver/proxy	0.050s

This is because the subscription to changes might happen before or
after the Node is advertised. Using a nonbuffered channel in combination
 with synctest to ensure we always receive the initial test announcement
 .